# Generated by Django 3.1.7 on 2021-04-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='author',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='call',
            name='verdict',
            field=models.TextField(blank=True, default='', verbose_name='Вердикт'),
        ),
    ]
