# Generated by Django 3.1.7 on 2021-04-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='something',
            field=models.CharField(default='', max_length=16, verbose_name='Something'),
        ),
    ]
