# Generated by Django 3.1.7 on 2021-04-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0005_customuser_something'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='something',
        ),
    ]
