# Generated by Django 3.1.7 on 2021-04-11 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0006_remove_customuser_something'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='author',
            field=models.ForeignKey(blank=True, default='', max_length=120, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
