# Generated by Django 3.2.5 on 2021-07-03 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0008_status_css_styles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='author',
            field=models.ForeignKey(blank=True, default='', max_length=120, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор обращения'),
        ),
    ]
